#!/usr/bin/env bash
set -eEuo pipefail

## Generate a list of age recipient keys based on a list of GitHub usernames read from .sops.users

exit() {
    echo "=== Exiting"
}

error_handler() {
    local exit_code=$?
    local line_number=$1
    echo "[ERROR] Command failed with exit code $exit_code at line $line_number" >&2
}

trap 'error_handler $LINENO' ERR
trap exit EXIT SIGINT SIGTERM

RECIPIENTS_FILE=".sops.recipients"
ALL_KEYS=()

get_keys_for_user() {
    local username="$1"

    echo "== Getting keys for: $username"

    local keys_url="https://github.com/${username}.keys"

    if ! keys_list="$(curl -s --show-error --fail "$keys_url")"
    then
        echo "[WARN] Failed to get user's keys - skipping"
        return
    fi

    echo "# ${username}:" >> "$RECIPIENTS_FILE"
    local count=0

    mapfile -t ssh_keys <<< "$keys_list"
    for key in "${ssh_keys[@]}"
    do
        ## Only ssh-ed25519 and ssh-rsa keys
        if [[ "$key" =~ ^ssh-(ed25519|rsa)[[:space:]]  ]]
        then
            echo "$key" >> "$RECIPIENTS_FILE"
            ALL_KEYS+=("$key")
            ((++count))
        fi
    done
    echo "Found $count keys"
}

## Write recipients file header
cat <<EOF > "$RECIPIENTS_FILE"
##
## sops/age recipient public keys
## This file was generated by sops_gen_recipients.sh, DO NOT MANUALLY EDIT
##

EOF

mapfile -t usernames < .sops.users

for line in "${usernames[@]}"
do
    ## Ignore comments
    if [[ "$line" =~ ^[[:space:]]*\#.*$ ]]
    then
        continue
    fi

    ## remove all whitespace from username line
    get_keys_for_user "${line//[[:space:]]/}"
done

## Write keys to .sops.yaml
echo "=== Writing ${#ALL_KEYS[@]} keys to sops config"
# clear existing
yq -i '.creation_rules[].age = []' .sops.yaml
# add keys
for key in "${ALL_KEYS[@]}"
do
    key="$key" yq -i '.creation_rules[].age += strenv(key)' .sops.yaml
done

## Re-encrypt secret files
echo "=== Updating keys "
for file in $(find secrets -name "*.enc.yaml" -type f)
do
    sops updatekeys -y "$file"
done