apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummyapp-pr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: nrao
          repo: dummy-app
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - preview
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'dummyapp-pr-{{.number}}'
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.github: ""
    spec:
      project: releng-dummyapp-demo
      sources:
      - path: helm-dummyapp
        repoURL: https://github.com/nrao/dummy-app.git
        targetRevision: '{{.head_sha}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - $values/common/dummyapp-values.yaml
            - $values/common/dummyapp-secrets.enc.yaml
            - $values/variants/local/dummyapp-values.yaml
            - $values/envs/local-dev/dummyapp-values.yaml
            - ../tests/preview/pr-{{.number}}-values.yaml
          values: |
            contextPath: '/pr-{{.number}}'
            ingress:
              hosts:
                - host: 'dummy-preview.localhost'
                  paths:
                    - path: '/pr-{{.number}}'
                      pathType: Prefix
      - repoURL: git@github.com:kdion-nrao/gitops-envs-test.git
        targetRevision: HEAD
        ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: dummyapp-preview-pr-{{.number}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
