apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dummy-app-deployments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            chartRev: HEAD
          - env: qa
            chartRev: "helmchart-v0.4.0"
  template:
    metadata:
      name: 'dummy-app-{{.env}}'
      labels:
        team: releng
        app: dummyapp
        env: '{{.env}}'
    spec:
      project: releng-dummyapp-demo
      sources:
        - repoURL: 'https://github.com/nrao/dummy-app/'
          path: helm-dummyapp
          targetRevision: '{{.chartRev}}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/common/dummyapp-values.yaml
              - $values/common/dummyapp-secrets.enc.yaml
              - $values/variants/local/dummyapp-values.yaml
              - $values/envs/local-{{.env}}/dummyapp-values.yaml
        - repoURL: git@github.com:kdion-nrao/gitops-envs-test.git
          targetRevision: HEAD
          ref: values
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'dummyapp-{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
